name: Get Spec

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install .
          pip install pyinstaller

      # Compile the application for macOS
      - name: Compile for macOS
        run: pyinstaller main.py
          
      # Upload the macOS DMG artifact
      - name: Upload macOS spec artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-spec
          path: main.spec

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install .
          pip install pyinstaller
          
      # Compile the application for Windows
      - name: Compile for Windows
        run: pyinstaller main.py

      # Upload the compiled artifact
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-compiled
          path: main.spec
